In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 선형 회귀

In [2]:
torch.manual_seed(777) # 랜덤 seed 설정

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [24]:
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.Adam([W, b], lr=0.01)

epochs = 1000
for epoch in range(epochs):
    hypothesis = x_train * W + b
    
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        ))
    

Epoch    0/1000 W: 0.010, b: 0.010 Cost: 18.666666
Epoch  100/1000 W: 0.857, b: 0.847 Cost: 3.003903
Epoch  200/1000 W: 1.275, b: 1.210 Cost: 0.414147
Epoch  300/1000 W: 1.412, b: 1.250 Cost: 0.236496
Epoch  400/1000 W: 1.465, b: 1.182 Cost: 0.203832
Epoch  500/1000 W: 1.507, b: 1.093 Cost: 0.173795
Epoch  600/1000 W: 1.550, b: 0.998 Cost: 0.145013
Epoch  700/1000 W: 1.593, b: 0.902 Cost: 0.118445
Epoch  800/1000 W: 1.636, b: 0.807 Cost: 0.094712
Epoch  900/1000 W: 1.678, b: 0.713 Cost: 0.074131


# nn을 사용한 선형 회귀

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [22]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.8362]], requires_grad=True), Parameter containing:
tensor([-0.0177], requires_grad=True)]


In [32]:
model = nn.Linear(1,1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

epoch_count = 1000

for epoch in range(epoch_count):
    
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    
    cost.backward()
    
    optimizer.step()
    if (epoch + 1) % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch + 1, epoch_count, cost.item()
      ))
    

Epoch  100/1000 Cost: 0.033940
Epoch  200/1000 Cost: 0.020973
Epoch  300/1000 Cost: 0.012960
Epoch  400/1000 Cost: 0.008008
Epoch  500/1000 Cost: 0.004949
Epoch  600/1000 Cost: 0.003058
Epoch  700/1000 Cost: 0.001890
Epoch  800/1000 Cost: 0.001168
Epoch  900/1000 Cost: 0.000722
Epoch 1000/1000 Cost: 0.000446


In [33]:
# 다중 선형 회귀

In [34]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [35]:
x_train.shape

torch.Size([5, 3])

In [40]:
list(model.parameters())

[Parameter containing:
 tensor([[0.4403, 0.4401, 0.2589]], requires_grad=True),
 Parameter containing:
 tensor([0.0038], requires_grad=True)]

In [41]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
epoch_count = 1000
for epoch in range(epoch_count):
    
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    
    cost.backward()
    
    optimizer.step()
    
    if (epoch + 1) % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch + 1, epoch_count, cost.item()
      ))
    

Epoch  100/1000 Cost: 0.290817
Epoch  200/1000 Cost: 0.284276
Epoch  300/1000 Cost: 0.278076
Epoch  400/1000 Cost: 0.272202
Epoch  500/1000 Cost: 0.266642
Epoch  600/1000 Cost: 0.261367
Epoch  700/1000 Cost: 0.256375
Epoch  800/1000 Cost: 0.251649
Epoch  900/1000 Cost: 0.247160
Epoch 1000/1000 Cost: 0.242911


In [44]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var)
pred_y

tensor([[151.0890]], grad_fn=<AddmmBackward0>)