In [1]:
import torch
import numpy as np

In [2]:
# 배열로 부터 초기화
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
data_np = np.array(data)
x_data_from_np = torch.tensor(data_np)

In [4]:
x_data_from_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7137, 0.1469],
        [0.9097, 0.2008]]) 

